---
title: "Untitled"
output: html_document
date: "2024-10-29"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## 2Dだけの効果量だす

データ読み込み

```{r}
library(effectsize)
library(emmeans)
library(ggplot2)
library(multcomp)
library(dplyr)
library(readr)
library(pwr)
source("functions.R")
```

```{r}
# formからのデータをよみだす
form_data = read.csv("csv/answer.csv", header = TRUE, sep = ",")

# ID(ファイル名)を取得
ids = form_data[, 7]
print(ids)

# 分析用dfを作っておく
df = data.frame(
  displayFormat = character(), # 表示形式
  incongruency = character(), # 一致不一致
  RT_ave = numeric() # RT
)

file_names = c("controll", "2D", "barrier", "Far")
```

```{r}
for(id in ids){
  display_format = "2D"
    
  # パスつくる
  path = paste0("csv/", id, "/")
  
  # csv読み出し
  response_data = read.csv(paste0(path, id, file_name,".csv"), header = TRUE, sep = ",")
  
  # 要因ごとに処理
  congruent_data = chose_by_incongruency(response_data, "congruent")
  filtered_congruent = remove_unnecessary_data(congruent_data)
  congruent_ave = mean(filtered_congruent$RT, na.rm = TRUE)
  df = add_row(df, display_format, "congruent", congruent_ave)
  
  incongruent_data = chose_by_incongruency(response_data, "incongruent")
  filtered_incongruent = remove_unnecessary_data(incongruent_data)
  incongruent_ave = mean(filtered_incongruent$RT, na.rm = TRUE)
  df = add_row(df, display_format, "incongruent", incongruent_ave)
}
```

```{r}
View(df)
write.csv(df, "2d_df.csv")
```

効果量の計算

```{r}
mean_RT <- aggregate(RT_ave ~ displayformat + incongruency, df, mean)
print(mean_RT)
ave_c = mean_RT[1, 3]
ave_i = mean_RT[2, 3]
print(ave_c)
print(ave_i)

var_RT <- aggregate(RT_ave ~ displayformat + incongruency, df, stats::var)
var_c = var_RT[1, 3]
var_i = var_RT[2, 3]
print(var_c)
print(var_i)

n_c = 20
n_i = 20

Sc = sqrt((n_c * var_c * var_c + n_i * var_i * var_i)/(n_c + n_i))
d = abs(ave_c - ave_i) / Sc
print(d)

# 同じ対象者からに会測定した得点の
d = 
```

# 全部合わせた効果量

```{r}
# df初期化
df = data.frame(
  displayFormat = character(), # 表示形式
  incongruency = character(), # 一致不一致
  RT_ave = numeric() # RT
)


for(id in ids){
  
  for (file_name in file_names){
    display_format = get_display_format(file_name)
    
    # パスつくる
    path = paste0("csv/", id, "/")
    
    # csv読み出して確認
    response_data = read.csv(paste0(path, id, file_name,".csv"), header = TRUE, sep = ",")
    paste0(path, id, file_name,".csv")
    # View(response_data)
    
    # 要因ごとに処理
    congruent_data = chose_by_incongruency(response_data, "congruent")
    filtered_congruent = remove_unnecessary_data(congruent_data)
    congruent_ave = mean(filtered_congruent$RT, na.rm = TRUE)
    df = add_row(df, display_format, "congruent", congruent_ave)
    
    incongruent_data = chose_by_incongruency(response_data, "incongruent")
    filtered_incongruent = remove_unnecessary_data(incongruent_data)
    incongruent_ave = mean(filtered_incongruent$RT, na.rm = TRUE)
    df = add_row(df, display_format, "incongruent", incongruent_ave)
    
  }

}
```

```{r}
View(df)
```

```{r}
mean_RT <- aggregate(RT_ave ~ incongruency, df, mean)
print(mean_RT)
ave_c = mean_RT[1, 2]
ave_i = mean_RT[2, 2]
print(ave_c)
print(ave_i)

var_RT <- aggregate(RT_ave ~ incongruency, df, stats::var)
print(var_RT)
var_c = var_RT[1, 2]
var_i = var_RT[2, 2]
print(var_c)
print(var_i)

n_c = 80
n_i = 80

Sc = sqrt((n_c * var_c * var_c + n_i * var_i * var_i)/(n_c + n_i))
d = abs(ave_c - ave_i) / Sc
print(d)
```
